// src/components/ContentCreator.vue
<script setup lang="ts">
type ContentType = 'post' | 'daily' | 'product' | 'interest'

interface Field {
  key: string
  label: string
  type: 'text' | 'date' | 'textarea' | 'select'
  required: boolean
  options?: string[]
  default?: string
}

interface ContentConfig {
  type: ContentType
  label: string
  directory: string
  extension: string
  fields: Field[]
}

const contentConfigs: Record<ContentType, ContentConfig> = {
  post: {
    type: 'post',
    label: '博客文章',
    directory: 'pages/posts',
    extension: '.md',
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'date', label: '日期', type: 'date', required: true },
      { key: 'lang', label: '语言', type: 'select', required: false, options: ['zh', 'en'], default: 'zh' },
      { key: 'duration', label: '阅读时长', type: 'text', required: false },
      { key: 'description', label: '描述', type: 'textarea', required: false },
    ],
  },
  daily: {
    type: 'daily',
    label: '碎记',
    directory: 'pages/content/daily',
    extension: '.md',
    fields: [
      { key: 'date', label: '日期', type: 'date', required: true },
    ],
  },
  product: {
    type: 'product',
    label: '产品',
    directory: 'pages/content/product',
    extension: '.md',
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'date', label: '日期', type: 'date', required: true },
      { key: 'category', label: '分类', type: 'select', required: true, options: ['cli-tool', 'design-system', 'node-framework', 'vite-plugin', 'vue-components', 'other'] },
      { key: 'description', label: '描述', type: 'textarea', required: false },
      { key: 'link', label: '链接', type: 'text', required: false },
      { key: 'github', label: 'GitHub 链接', type: 'text', required: false },
    ],
  },
  interest: {
    type: 'interest',
    label: '兴趣',
    directory: 'pages/content/interest',
    extension: '.md',
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'date', label: '日期', type: 'date', required: true },
      { key: 'description', label: '描述', type: 'textarea', required: false },
      { key: 'category', label: '分类', type: 'text', required: false },
    ],
  },
}

// Form state
const selectedType = ref<ContentType>('post')
const formData = ref<Record<string, string>>({})
const content = ref('')
const generatedMd = ref('')
const showModal = ref(false)
const previewFilename = ref('')
const showPreview = ref(false)
const copied = ref(false)

const currentConfig = computed(() => contentConfigs[selectedType.value])

// Reset form when type changes
watch(selectedType, () => {
  formData.value = {}
  content.value = ''
  generatedMd.value = ''
  showPreview.value = false

  // Set defaults
  currentConfig.value.fields.forEach((field) => {
    if (field.default) {
      formData.value[field.key] = field.default
    }
  })
})

// Generate markdown preview
function generateMarkdown() {
  const config = currentConfig.value
  const frontmatter: Record<string, any> = {}

  config.fields.forEach((field) => {
    if (field.key === 'draft') {
      frontmatter[field.key] = formData.value[field.key] === 'true'
    }
    else if (formData.value[field.key]) {
      frontmatter[field.key] = formData.value[field.key]
    }
  })

  let filename: string
  if (selectedType.value === 'daily') {
    filename = `${formData.value.date || new Date().toISOString().split('T')[0]}.md`
  }
  else {
    const title = formData.value.title || 'untitled'
    filename = `${slugify(title)}.md`
  }

  let md = '---\n'
  Object.entries(frontmatter).forEach(([key, value]) => {
    md += `${key}: ${value}\n`
  })
  md += '---\n\n'

  if (selectedType.value !== 'daily') {
    md += content.value
  }
  else {
    md += content.value
  }

  generatedMd.value = md
  previewFilename.value = filename
  showModal.value = true
  return { filename, md }
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-{2,}/g, '-')
    .trim()
}

async function copyToClipboard() {
  try {
    await navigator.clipboard.writeText(generatedMd.value)
    copied.value = true
    setTimeout(() => {
      copied.value = false
    }, 2000)
  }
  catch {
    // silent fail
  }
}

function downloadFile() {
  const { filename, md } = generateMarkdown()
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// Initialize
onMounted(() => {
  selectedType.value = 'post'
})
</script>

<template>
  <div class="content-creator">
    <div class="creator-header">
      <h1 class="text-2xl font-bold">
        创建内容
      </h1>
      <p class="op60 mt-2">
        选择内容类型，填写表单，生成 Markdown 文件
      </p>
    </div>

    <!-- 类型选择 -->
    <div class="type-selector">
      <button
        v-for="(config, type) in contentConfigs"
        :key="type"
        class="type-btn"
        :class="{ active: selectedType === type }"
        @click="selectedType = type"
      >
        {{ config.label }}
      </button>
    </div>

    <!-- 表单 -->
    <div class="form-section">
      <div class="form-grid">
        <div
          v-for="field in currentConfig.fields"
          :key="field.key"
          class="form-field"
          :class="{ required: field.required }"
        >
          <label :for="field.key">{{ field.label }}</label>

          <select
            v-if="field.type === 'select'"
            :id="field.key"
            v-model="formData[field.key]"
          >
            <option value="">
              请选择
            </option>
            <option
              v-for="opt in field.options"
              :key="opt"
              :value="opt"
            >
              {{ opt }}
            </option>
          </select>

          <textarea
            v-else-if="field.type === 'textarea'"
            :id="field.key"
            v-model="formData[field.key]"
            rows="3"
          />

          <input
            v-else
            :id="field.key"
            v-model="formData[field.key]"
            :type="field.type"
          >
        </div>
      </div>

      <!-- 正文输入 -->
      <div v-if="selectedType !== 'daily'" class="content-field">
        <label for="content">正文内容 (Markdown)</label>
        <textarea
          id="content"
          v-model="content"
          rows="12"
          placeholder="输入正文内容，支持 Markdown 格式..."
        />
      </div>

      <div v-else class="content-field">
        <label for="content">碎记内容</label>
        <textarea
          id="content"
          v-model="content"
          rows="12"
          placeholder="输入碎记内容..."
        />
      </div>

      <!-- 预览 & 生成 -->
      <div class="actions">
        <button class="btn-secondary" @click="generateMarkdown">
          <div i-ri-eye-line />
          预览
        </button>
        <button class="btn-primary" @click="downloadFile">
          <div i-ri-download-line />
          下载
        </button>
        <button class="btn-secondary" @click="copyToClipboard">
          <div :class="copied ? 'i-ri-check-line' : 'i-ri-clipboard-line'" />
          {{ copied ? '已复制' : '复制' }}
        </button>
      </div>
    </div>

    <!-- 预览模态框 -->
    <Teleport to="body">
      <div v-if="showModal" class="modal-overlay" @click.self="showModal = false">
        <div class="modal-content">
          <div class="modal-header">
            <h3>预览 - {{ currentConfig.directory }}/{{ previewFilename }}</h3>
            <button class="modal-close" @click="showModal = false">
              <div i-ri-close-line />
            </button>
          </div>
          <pre class="modal-preview"><code>{{ generatedMd }}</code></pre>
          <div class="modal-actions">
            <button class="btn-secondary" @click="copyToClipboard">
              <div :class="copied ? 'i-ri-check-line' : 'i-ri-clipboard-line'" />
              {{ copied ? '已复制' : '复制' }}
            </button>
            <button class="btn-primary" @click="downloadFile">
              <div i-ri-download-line />
              下载
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.content-creator {
  max-width: 900px;
  margin: 0 auto;
  padding: 2rem 1rem;
}

.creator-header {
  margin-bottom: 2rem;
}

.type-selector {
  display: flex;
  gap: 0.75rem;
  margin-bottom: 2rem;
  flex-wrap: wrap;
}

.type-btn {
  padding: 0.75rem 1.5rem;
  border-radius: 0.75rem;
  border: 1px solid var(--c-border);
  background: var(--c-bg);
  cursor: pointer;
  transition: all 0.2s;
  font-weight: 500;
}

.type-btn:hover {
  border-color: var(--c-text);
}

.type-btn.active {
  background: linear-gradient(135deg, #667eea, #764ba2);
  color: white;
  border-color: transparent;
}

.form-section {
  background: var(--c-bg-soft);
  border-radius: 1rem;
  /* padding: 1.5rem; */
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.form-field.required label::after {
  content: ' *';
  color: #ff6b6b;
}

.form-field input,
.form-field select,
.form-field textarea {
  padding: 0.8rem;
  border: 1px solid #d1d5db;
  border-radius: 0.5rem;
  background: var(--c-bg);
  font-size: 0.875rem;
  transition: border-color 0.2s;
  line-height: 1;
}

.form-field input:focus,
.form-field select:focus,
.form-field textarea:focus {
  outline: none;
  border-color: #667eea;
}

.content-field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.content-field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.content-field textarea {
  padding: 0.75rem;
  border: 1px solid var(--c-border);
  border-radius: 0.5rem;
  background: var(--c-bg);
  font-size: 0.875rem;
  resize: vertical;
  font-family: inherit;
}

.content-field textarea:focus {
  outline: none;
  border-color: #667eea;
}

.actions {
  display: flex;
  gap: 0.75rem;
  justify-content: flex-end;
}

.btn-primary,
.btn-secondary {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.25rem;
  border-radius: 0.5rem;
  border: none;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.2s;
}

.btn-primary {
  background: linear-gradient(135deg, #667eea, #764ba2);
  color: white;
}

.btn-primary:hover {
  opacity: 0.9;
  transform: translateY(-1px);
}

.btn-secondary {
  background: var(--c-bg);
  border: 1px solid var(--c-border);
  color: var(--c-text);
}

.btn-secondary:hover {
  border-color: var(--c-text);
}

/* Modal styles */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 2rem;
}

.modal-content {
  background: var(--c-bg);
  border-radius: 1rem;
  width: 100%;
  max-width: 800px;
  max-height: 80vh;
  display: flex;
  flex-direction: column;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.2);
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 1.5rem;
  border-bottom: 1px solid var(--c-border);
}

.modal-header h3 {
  font-weight: 600;
  font-size: 0.875rem;
}

.modal-close {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0.5rem;
  opacity: 0.6;
  transition: opacity 0.2s;
}

.modal-close:hover {
  opacity: 1;
}

.modal-preview {
  flex: 1;
  overflow: auto;
  padding: 1.5rem;
  margin: 0;
  font-size: 0.875rem;
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-all;
}

.modal-actions {
  display: flex;
  gap: 0.75rem;
  justify-content: flex-end;
  padding: 1rem 1.5rem;
  border-top: 1px solid var(--c-border);
}
</style>

// content-creator/src/components/ContentCreator.tsx
'use client'

import { contentConfigs, type ContentType, generateFilename, generateMarkdown } from '@/lib/config'
import { useEffect, useState } from 'react'

export default function ContentCreator() {
  const [selectedType, setSelectedType] = useState<ContentType>('post')
  const [formData, setFormData] = useState<Record<string, string | string[]>>({})
  const [content, setContent] = useState('')
  const [copied, setCopied] = useState(false)
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'success' | 'error'>('idle')
  const [toast, setToast] = useState<string | null>(null)
  const [previewMd, setPreviewMd] = useState('')
  const [showPreview, setShowPreview] = useState(false)

  const currentConfig = contentConfigs[selectedType]

  // Generate real-time preview markdown
  useEffect(() => {
    const md = generateMarkdown(selectedType, formData, content)
    setPreviewMd(md)
  }, [selectedType, formData, content, currentConfig])

  // Simple markdown to HTML converter
  function markdownToHtml(md: string): string {
    let html = md
      // Escape HTML
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      // Code blocks
      .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre class="bg-gray-100 dark:bg-gray-800 rounded p-3 my-2 overflow-x-auto"><code>$2</code></pre>')
      // Inline code
      .replace(/`([^`]+)`/g, '<code class="bg-gray-100 dark:bg-gray-800 px-1 rounded">$1</code>')
      // Headers
      .replace(/^### (.+)$/gm, '<h3 class="text-lg font-semibold mt-4 mb-2">$1</h3>')
      .replace(/^## (.+)$/gm, '<h2 class="text-xl font-semibold mt-4 mb-2">$1</h2>')
      .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold mt-4 mb-2">$1</h1>')
      // Bold
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      // Italic
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      // Links
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" class="text-purple-600 hover:underline" target="_blank" rel="noopener">$1</a>')
      // Images
      .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" class="max-w-full rounded-lg my-2" />')
      // Unordered lists
      .replace(/^- (.+)$/gm, '<li class="ml-4 list-disc">$1</li>')
      // Paragraphs
      .replace(/\n\n/g, '</p><p class="my-2">')
      // Line breaks
      .replace(/\n/g, '<br />')

    // Wrap in paragraph
    html = `<p class="my-2">${html}</p>`

    // Clean up empty paragraphs
    html = html.replace(/<p class="my-2"><\/p>/g, '')
    html = html.replace(/<p class="my-2"><br \/>/g, '<p class="my-2">')

    return html
  }

  // Set defaults when type changes (component remounts due to key)
  useEffect(() => {
    const defaults: Record<string, string> = {}
    currentConfig.fields.forEach((field) => {
      if (field.default) {
        defaults[field.key] = field.default
      }
    })
    setFormData(defaults)
    setContent('')
  }, [selectedType, currentConfig])

  function handleFieldChange(key: string, value: string) {
    setFormData(prev => ({ ...prev, [key]: value }))
  }

  function handleImageUpload(event: React.ChangeEvent<HTMLInputElement>, key: string) {
    const file = event.target.files?.[0]
    if (!file)
      return

    const reader = new FileReader()
    reader.onload = (e) => {
      setFormData(prev => ({ ...prev, [key]: e.target?.result as string }))
    }
    reader.readAsDataURL(file)
  }

  function handleMultipleImageUpload(event: React.ChangeEvent<HTMLInputElement>, key: string) {
    const files = Array.from(event.target.files || [])
    if (files.length === 0)
      return

    const readers = files.map((file) => {
      return new Promise<string>((resolve) => {
        const reader = new FileReader()
        reader.onload = e => resolve(e.target?.result as string)
        reader.readAsDataURL(file)
      })
    })

    Promise.all(readers).then((results) => {
      setFormData((prev) => {
        const existing = prev[key]
        const existingArray = Array.isArray(existing) ? existing : existing ? [existing] : []
        return { ...prev, [key]: [...existingArray, ...results] }
      })
    })
  }

  function removeImage(key: string, index: number) {
    setFormData((prev) => {
      const existing = prev[key]
      if (!Array.isArray(existing))
        return prev
      const newArray = existing.filter((_, i) => i !== index)
      return { ...prev, [key]: newArray }
    })
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(previewMd)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
    catch {
      // silent fail
    }
  }

  async function saveFile() {
    // Validate required fields
    const missingFields = currentConfig.fields
      .filter(field => field.required && !formData[field.key])
      .map(field => field.label)

    if (missingFields.length > 0) {
      setToast(`请填写必填字段: ${missingFields.join(', ')}`)
      setTimeout(() => setToast(null), 3000)
      return
    }

    setSaveStatus('saving')

    try {
      const response = await fetch('/api/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: selectedType, fields: formData, content }),
      })

      const result = await response.json()

      if (result.success) {
        setSaveStatus('success')
        setToast('保存成功')
        setTimeout(() => {
          setSaveStatus('idle')
          setToast(null)
        }, 2000)
      }
      else {
        throw new Error(result.error)
      }
    }
    catch {
      setSaveStatus('error')
      setToast('保存失败')
      setTimeout(() => {
        setSaveStatus('idle')
        setToast(null)
      }, 3000)
    }
  }

  function downloadFile() {
    const md = generateMarkdown(selectedType, formData, content)
    const filename = generateFilename(selectedType, formData)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Navbar */}
      <header className="fixed top-0 left-0 right-0 z-40 h-16 px-6 flex items-center border-b border-gray-200 dark:border-gray-700 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md">
        <div className="flex items-center gap-3">
          <span className="text-xl font-bold bg-gradient-to-r from-purple-600 to-pink-500 bg-clip-text text-transparent">Rex Wang</span>
        </div>

        {/* Action buttons in navbar */}
        <div className="flex-1 flex justify-end gap-2">
          <button
            onClick={() => setShowPreview(prev => !prev)}
            className={`w-20 py-1.5 rounded-lg transition-colors flex items-center justify-center gap-1 text-sm ${
              showPreview ? 'bg-purple-100 dark:bg-purple-900 text-purple-600' : 'hover:bg-gray-200 dark:hover:bg-gray-700'
            }`}
          >
            <span>👁️</span>
            {' '}
            {showPreview ? '关闭' : '预览'}
          </button>
          <button
            onClick={saveFile}
            disabled={saveStatus === 'saving'}
            className="w-20 py-1.5 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors flex items-center justify-center gap-1 text-sm disabled:opacity-60"
          >
            <span>💾</span>
            {' '}
            保存
          </button>
          <button
            onClick={downloadFile}
            className="w-20 py-1.5 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors flex items-center justify-center gap-1 text-sm"
          >
            <span>📥</span>
            {' '}
            下载
          </button>
          <button
            onClick={copyToClipboard}
            className="w-20 py-1.5 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors flex items-center justify-center gap-1 text-sm"
          >
            <span>{copied ? '✅' : '📋'}</span>
            {' '}
            {copied ? '已复制' : '复制'}
          </button>
        </div>

        <nav className="flex items-center gap-1 ml-4">
          <a href="https://github.com/OnlyProbie" target="_blank" rel="noopener noreferrer" className="px-3 py-2 rounded-lg opacity-60 hover:opacity-100 transition-opacity">
            GitHub
          </a>
        </nav>
      </header>

      {/* Main Content */}
      <div className="flex flex-1 mx-auto mt-16">
        {/* Middle - Form */}
        <div className="flex-1 w-[900px]">
          <div key={selectedType} className="max-w-[700px] mx-auto">
            {/* Type selector at top of form */}
            <div className="flex gap-2 mb-6 flex-wrap pt-5">
              {Object.entries(contentConfigs).map(([type, config]) => (
                <button
                  key={type}
                  onClick={() => setSelectedType(type as ContentType)}
                  className={`w-28 py-2 rounded-lg border font-medium transition-all text-sm ${
                    selectedType === type
                      ? 'bg-gradient-to-r from-purple-600 via-pink-500 to-purple-600 bg-[length:200%_100%] animate-gradient text-white border-transparent'
                      : 'bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 hover:border-purple-500'
                  }`}
                >
                  {config.label}
                </button>
              ))}
              <span className="ml-auto text-sm text-gray-500 self-center">{currentConfig.directory}</span>
            </div>

            {/* Form */}
            <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl p-6 mb-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                {currentConfig.fields.map(field => (
                  <div key={field.key} className={`flex flex-col gap-2 ${field.type === 'textarea' || field.type === 'image' || field.type === 'images' ? 'md:col-span-2' : ''}`}>
                    <label className="text-sm font-medium">
                      {field.label}
                      {field.required && <span className="text-red-500 ml-1">*</span>}
                    </label>

                    {field.type === 'select'
                      ? (
                          <select
                            value={formData[field.key] || ''}
                            onChange={e => handleFieldChange(field.key, e.target.value)}
                            className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 focus:outline-none focus:border-purple-500"
                          >
                            <option value="">请选择</option>
                            {field.options?.map(opt => (
                              <option key={opt} value={opt}>{opt}</option>
                            ))}
                          </select>
                        )
                      : field.type === 'textarea'
                        ? (
                            <textarea
                              value={formData[field.key] || ''}
                              onChange={e => handleFieldChange(field.key, e.target.value)}
                              rows={3}
                              className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 focus:outline-none focus:border-purple-500 resize-none"
                            />
                          )
                        : field.type === 'image'
                          ? (
                              <div className="flex flex-wrap gap-2 items-center">
                                {formData[field.key] && typeof formData[field.key] === 'string'
                                  ? (
                                      <div className="relative w-24 h-20">
                                        <img
                                          src={formData[field.key] as string}
                                          alt="Preview"
                                          className="w-full h-full object-cover rounded-lg border"
                                        />
                                        <button
                                          type="button"
                                          onClick={() => setFormData(prev => ({ ...prev, [field.key]: '' }))}
                                          className="absolute -top-2 -right-2 w-5 h-5 bg-red-500 text-white rounded-full text-xs flex items-center justify-center hover:bg-red-600"
                                        >
                                          ×
                                        </button>
                                      </div>
                                    )
                                  : (
                                      <label className="cursor-pointer inline-flex w-24 h-20 items-center justify-center bg-gray-100 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg hover:border-purple-500 transition-colors">
                                        <span>📤</span>
                                        <input
                                          type="file"
                                          accept="image/*"
                                          onChange={e => handleImageUpload(e, field.key)}
                                          className="hidden"
                                        />
                                      </label>
                                    )}
                              </div>
                            )
                          : field.type === 'images'
                            ? (
                                <div className="flex flex-wrap gap-2 items-center">
                                  {Array.isArray(formData[field.key]) && (formData[field.key] as string[]).map((src, idx) => (
                                    <div key={idx} className="relative w-24 h-20">
                                      <img
                                        src={src}
                                        alt={`Preview ${idx + 1}`}
                                        className="w-full h-full object-cover rounded-lg border"
                                      />
                                      <button
                                        type="button"
                                        onClick={() => removeImage(field.key, idx)}
                                        className="absolute -top-2 -right-2 w-5 h-5 bg-red-500 text-white rounded-full text-xs flex items-center justify-center hover:bg-red-600"
                                      >
                                        ×
                                      </button>
                                    </div>
                                  ))}
                                  <label className="cursor-pointer inline-flex w-24 h-20 items-center justify-center bg-gray-100 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg hover:border-purple-500 transition-colors">
                                    <span>📤</span>
                                    <input
                                      type="file"
                                      accept="image/*"
                                      multiple
                                      onChange={e => handleMultipleImageUpload(e, field.key)}
                                      className="hidden"
                                    />
                                  </label>
                                </div>
                              )
                            : (
                                <input
                                  type={field.type}
                                  value={formData[field.key] || ''}
                                  onChange={e => handleFieldChange(field.key, e.target.value)}
                                  className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 focus:outline-none focus:border-purple-500"
                                />
                              )}
                  </div>
                ))}
              </div>

              {/* Content input */}
              <div className="mb-6">
                <label className="text-sm font-medium block mb-2">
                  {selectedType === 'daily' ? '碎记内容' : '正文内容 (Markdown)'}
                </label>
                <textarea
                  value={content}
                  onChange={e => setContent(e.target.value)}
                  rows={12}
                  placeholder={selectedType === 'daily' ? '输入碎记内容...' : '输入正文内容，支持 Markdown 格式...'}
                  className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 focus:outline-none focus:border-purple-500 resize-y font-mono text-sm"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Real-time Preview Panel */}
      <div
        className={`fixed top-16 right-0 w-100 h-[calc(100vh-4rem)] overflow-auto border-l border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-4 transition-transform duration-300 ease-in-out ${
          showPreview ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        <h3 className="font-semibold text-sm text-gray-500 dark:text-gray-400 mb-3">实时预览</h3>
        <div
          className="text-sm text-gray-800 dark:text-gray-200"
          dangerouslySetInnerHTML={{ __html: markdownToHtml(previewMd) }}
        />
      </div>

      {/* Toast Notification */}
      {toast && (
        <div className="fixed top-20 left-1/2 -translate-x-1/2 z-50 px-6 py-3 bg-orange-500 text-white rounded-lg shadow-lg text-sm">
          {toast}
        </div>
      )}
    </div>
  )
}
